"""Dependency-free SVG charts with a consistent scientific-report style."""

from __future__ import annotations

from collections import Counter
from collections.abc import Mapping, Sequence
from html import escape
from pathlib import Path
from statistics import mean, median


_INK = "#0f172a"
_MUTED = "#64748b"
_GRID = "#cbd5e1"
_PANEL = "#f8fafc"
_BLUE = "#2563eb"
_TEAL = "#0f766e"


def _header(width: int, height: int, title: str, description: str) -> list[str]:
    """Return the common accessible SVG header and theme."""

    return [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img">',
        f"<title>{escape(title)}</title>",
        f"<desc>{escape(description)}</desc>",
        "<style>text{font-family:Inter,Segoe UI,Arial,sans-serif}</style>",
        f'<rect width="100%" height="100%" rx="16" fill="{_PANEL}"/>',
        f'<text x="48" y="48" fill="{_INK}" font-size="25" font-weight="700">{escape(title)}</text>',
        f'<text x="48" y="74" fill="{_MUTED}" font-size="14">{escape(description)}</text>',
    ]


def _footer(elements: list[str], width: int, height: int) -> None:
    """Append the shared footer and closing tag to an SVG element list."""

    elements.extend(
        [
            f'<line x1="48" y1="{height - 34}" x2="{width - 48}" y2="{height - 34}" stroke="{_GRID}"/>',
            f'<text x="{width - 48}" y="{height - 14}" text-anchor="end" fill="{_MUTED}" font-size="11">Generated by annostat</text>',
            "</svg>",
        ]
    )


def write_bar_chart(
    path: Path,
    title: str,
    counts: Mapping[str, int],
    *,
    description: str = "Counts across annotated coding sequences",
    axis_label: str = "Count",
    sort_by_value: bool = True,
    percentage_total: int | None = None,
) -> None:
    """Write an accessible horizontal SVG bar chart.

    Bars may be ordered by value or retain insertion order. When
    ``percentage_total`` is provided, each value label also includes its share of
    that total.
    """

    items = list(counts.items())
    if sort_by_value:
        items.sort(key=lambda item: (-item[1], item[0]))
    width = 1200
    left = 360
    right = 150 if percentage_total else 90
    top = 105
    row_height = 34
    plot_width = width - left - right
    height = max(230, top + row_height * len(items) + 80)
    maximum = max((value for _, value in items), default=1)
    elements = _header(width, height, title, description)

    for tick in range(5):
        x = left + plot_width * tick / 4
        value = round(maximum * tick / 4)
        elements.extend(
            [
                f'<line x1="{x:.1f}" y1="{top - 10}" x2="{x:.1f}" y2="{height - 72}" stroke="{_GRID}" stroke-dasharray="3 5"/>',
                f'<text x="{x:.1f}" y="{height - 50}" text-anchor="middle" fill="{_MUTED}" font-size="12">{value:,}</text>',
            ]
        )

    for index, (label, value) in enumerate(items):
        y = top + index * row_height
        bar_width = plot_width * value / maximum if maximum else 0
        color = _BLUE if index % 2 == 0 else _TEAL
        value_label = f"{value:,}"
        if percentage_total:
            value_label += f"  ({100 * value / percentage_total:.2f}%)"
        elements.extend(
            [
                f'<text x="{left - 14}" y="{y + 19}" text-anchor="end" fill="{_INK}" font-size="13">{escape(label)}</text>',
                f'<rect x="{left}" y="{y}" width="{bar_width:.1f}" height="23" rx="5" fill="{color}"/>',
                f'<text x="{left + bar_width + 8:.1f}" y="{y + 17}" fill="{_INK}" font-size="12" font-weight="600">{escape(value_label)}</text>',
            ]
        )
    elements.append(
        f'<text x="{left + plot_width / 2:.1f}" y="{height - 39}" text-anchor="middle" fill="{_MUTED}" font-size="12">{escape(axis_label)}</text>'
    )
    _footer(elements, width, height)
    path.write_text("\n".join(elements) + "\n", encoding="utf-8")


def write_histogram(path: Path, title: str, values: Sequence[int], bins: int = 20) -> None:
    """Write a CDS-length SVG histogram with mean and median markers.

    The requested bin count is treated as an upper target; integer-width bins are
    calculated from the observed range so every input length belongs to one bin.
    """

    width, height = 1200, 650
    left, right, top, bottom = 90, 48, 110, 100
    plot_width = width - left - right
    plot_height = height - top - bottom
    elements = _header(
        width,
        height,
        title,
        f"Distribution across {len(values):,} coding sequences",
    )
    if not values:
        elements.append(
            f'<text x="{width / 2}" y="{height / 2}" text-anchor="middle" fill="{_MUTED}" font-size="16">No CDS lengths available</text>'
        )
        _footer(elements, width, height)
        path.write_text("\n".join(elements) + "\n", encoding="utf-8")
        return

    minimum, maximum = min(values), max(values)
    span = max(1, maximum - minimum + 1)
    bin_width = max(1, (span + bins - 1) // bins)
    bin_count = (span + bin_width - 1) // bin_width
    histogram: Counter[int] = Counter((value - minimum) // bin_width for value in values)
    peak = max(histogram.values(), default=1)

    for tick in range(5):
        y = top + plot_height - plot_height * tick / 4
        count = round(peak * tick / 4)
        elements.extend(
            [
                f'<line x1="{left}" y1="{y:.1f}" x2="{width - right}" y2="{y:.1f}" stroke="{_GRID}" stroke-dasharray="3 5"/>',
                f'<text x="{left - 12}" y="{y + 4:.1f}" text-anchor="end" fill="{_MUTED}" font-size="12">{count:,}</text>',
            ]
        )

    slot_width = plot_width / bin_count
    for index in range(bin_count):
        count = histogram[index]
        bar_height = plot_height * count / peak
        x = left + index * slot_width + 2
        y = top + plot_height - bar_height
        elements.append(
            f'<rect x="{x:.1f}" y="{y:.1f}" width="{max(1, slot_width - 4):.1f}" height="{bar_height:.1f}" rx="3" fill="{_BLUE}"><title>{count:,} CDS</title></rect>'
        )
        if index % max(1, bin_count // 6) == 0 or index == bin_count - 1:
            label = minimum + index * bin_width
            elements.append(
                f'<text x="{x + slot_width / 2:.1f}" y="{top + plot_height + 24}" text-anchor="middle" fill="{_MUTED}" font-size="11">{label:,}</text>'
            )

    center_markers = ((median(values), "Median", _TEAL), (mean(values), "Mean", _BLUE))
    for marker_index, (value, label, color) in enumerate(center_markers):
        x = left + plot_width * (value - minimum) / span
        label_y = top + 17 + marker_index * 21
        elements.extend(
            [
                f'<line x1="{x:.1f}" y1="{top}" x2="{x:.1f}" y2="{top + plot_height}" stroke="{color}" stroke-width="2" stroke-dasharray="7 5"/>',
                f'<text x="{x + 7:.1f}" y="{label_y}" fill="{color}" font-size="12" font-weight="600">{label}: {value:,.0f} nt</text>',
            ]
        )

    elements.extend(
        [
            f'<text x="{left + plot_width / 2}" y="{height - 48}" text-anchor="middle" fill="{_INK}" font-size="13">CDS length (nucleotides)</text>',
            f'<text x="22" y="{top + plot_height / 2}" text-anchor="middle" fill="{_INK}" font-size="13" transform="rotate(-90 22 {top + plot_height / 2})">Number of CDS</text>',
        ]
    )
    _footer(elements, width, height)
    path.write_text("\n".join(elements) + "\n", encoding="utf-8")
