"""Dependency-free SVG charts with a consistent scientific-report style."""

from __future__ import annotations

from collections import Counter
from collections.abc import Mapping, Sequence
from html import escape
from pathlib import Path
from statistics import mean, median


_INK = "#0f172a"
_MUTED = "#64748b"
_GRID = "#cbd5e1"
_PANEL = "#f8fafc"
_BLUE = "#2563eb"
_TEAL = "#0f766e"


def _short_label(value: object, maximum: int = 30) -> str:
    """Shorten a visible plot label while preserving compact identifiers."""

    label = str(value)
    return label if len(label) <= maximum else label[: maximum - 1] + "…"


def _header(width: int, height: int, title: str, description: str) -> list[str]:
    """Return the common accessible SVG header and theme."""

    return [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img">',
        f"<title>{escape(title)}</title>",
        f"<desc>{escape(description)}</desc>",
        "<style>text{font-family:Inter,Segoe UI,Arial,sans-serif}</style>",
        f'<rect width="100%" height="100%" rx="16" fill="{_PANEL}"/>',
        f'<text x="48" y="48" fill="{_INK}" font-size="25" font-weight="700">{escape(title)}</text>',
        f'<text x="48" y="74" fill="{_MUTED}" font-size="14">{escape(description)}</text>',
    ]


def _footer(elements: list[str], width: int, height: int) -> None:
    """Append the shared footer and closing tag to an SVG element list."""

    elements.extend(
        [
            f'<line x1="48" y1="{height - 34}" x2="{width - 48}" y2="{height - 34}" stroke="{_GRID}"/>',
            f'<text x="{width - 48}" y="{height - 14}" text-anchor="end" fill="{_MUTED}" font-size="11">Generated by Annostat</text>',
            "</svg>",
        ]
    )


def write_bar_chart(
    path: Path,
    title: str,
    counts: Mapping[str, int],
    *,
    description: str = "Counts across annotated coding sequences",
    axis_label: str = "Count",
    sort_by_value: bool = True,
    percentage_total: int | None = None,
) -> None:
    """Write an accessible horizontal SVG bar chart.

    Bars may be ordered by value or retain insertion order. When
    ``percentage_total`` is provided, each value label also includes its share of
    that total.
    """

    items = list(counts.items())
    if sort_by_value:
        items.sort(key=lambda item: (-item[1], item[0]))
    width = 1200
    left = 360
    right = 150 if percentage_total else 90
    top = 105
    row_height = 34
    plot_width = width - left - right
    height = max(230, top + row_height * len(items) + 80)
    maximum = max((value for _, value in items), default=1)
    elements = _header(width, height, title, description)

    tick_values = sorted({round(maximum * tick / 4) for tick in range(5)})
    for value in tick_values:
        x = left + plot_width * value / maximum
        elements.extend(
            [
                f'<line x1="{x:.1f}" y1="{top - 10}" x2="{x:.1f}" y2="{height - 72}" stroke="{_GRID}" stroke-dasharray="3 5"/>',
                f'<text x="{x:.1f}" y="{height - 50}" text-anchor="middle" fill="{_MUTED}" font-size="12">{value:,}</text>',
            ]
        )

    for index, (label, value) in enumerate(items):
        y = top + index * row_height
        bar_width = plot_width * value / maximum if maximum else 0
        color = _BLUE if index % 2 == 0 else _TEAL
        value_label = f"{value:,}"
        if percentage_total:
            value_label += f"  ({100 * value / percentage_total:.2f}%)"
        elements.extend(
            [
                f'<text x="{left - 14}" y="{y + 19}" text-anchor="end" fill="{_INK}" font-size="13">{escape(label)}</text>',
                f'<rect x="{left}" y="{y}" width="{bar_width:.1f}" height="23" rx="5" fill="{color}"/>',
                f'<text x="{left + bar_width + 8:.1f}" y="{y + 17}" fill="{_INK}" font-size="12" font-weight="600">{escape(value_label)}</text>',
            ]
        )
    elements.append(
        f'<text x="{left + plot_width / 2:.1f}" y="{height - 39}" text-anchor="middle" fill="{_MUTED}" font-size="12">{escape(axis_label)}</text>'
    )
    _footer(elements, width, height)
    path.write_text("\n".join(elements) + "\n", encoding="utf-8")


def write_histogram(path: Path, title: str, values: Sequence[int], bins: int = 20) -> None:
    """Write a CDS-length SVG histogram with mean and median markers.

    The requested bin count is treated as an upper target; integer-width bins are
    calculated from the observed range so every input length belongs to one bin.
    """

    width, height = 1200, 650
    left, right, top, bottom = 90, 48, 110, 100
    plot_width = width - left - right
    plot_height = height - top - bottom
    elements = _header(
        width,
        height,
        title,
        f"Distribution across {len(values):,} coding sequences",
    )
    if not values:
        elements.append(
            f'<text x="{width / 2}" y="{height / 2}" text-anchor="middle" fill="{_MUTED}" font-size="16">No CDS lengths available</text>'
        )
        _footer(elements, width, height)
        path.write_text("\n".join(elements) + "\n", encoding="utf-8")
        return

    minimum, maximum = min(values), max(values)
    span = max(1, maximum - minimum + 1)
    bin_width = max(1, (span + bins - 1) // bins)
    bin_count = (span + bin_width - 1) // bin_width
    histogram: Counter[int] = Counter((value - minimum) // bin_width for value in values)
    peak = max(histogram.values(), default=1)

    tick_counts = sorted({round(peak * tick / 4) for tick in range(5)})
    for count in tick_counts:
        y = top + plot_height - plot_height * count / peak
        elements.extend(
            [
                f'<line x1="{left}" y1="{y:.1f}" x2="{width - right}" y2="{y:.1f}" stroke="{_GRID}" stroke-dasharray="3 5"/>',
                f'<text x="{left - 12}" y="{y + 4:.1f}" text-anchor="end" fill="{_MUTED}" font-size="12">{count:,}</text>',
            ]
        )

    slot_width = plot_width / bin_count
    for index in range(bin_count):
        count = histogram[index]
        bar_height = plot_height * count / peak
        x = left + index * slot_width + 2
        y = top + plot_height - bar_height
        elements.append(
            f'<rect x="{x:.1f}" y="{y:.1f}" width="{max(1, slot_width - 4):.1f}" height="{bar_height:.1f}" rx="3" fill="{_BLUE}"><title>{count:,} CDS</title></rect>'
        )
        if index % max(1, bin_count // 6) == 0 or index == bin_count - 1:
            label = minimum + index * bin_width
            elements.append(
                f'<text x="{x + slot_width / 2:.1f}" y="{top + plot_height + 24}" text-anchor="middle" fill="{_MUTED}" font-size="11">{label:,}</text>'
            )

    center_markers = ((median(values), "Median", _TEAL), (mean(values), "Mean", _BLUE))
    for marker_index, (value, label, color) in enumerate(center_markers):
        marker_span = max(1, maximum - minimum)
        x = left + plot_width * (value - minimum) / marker_span
        label_y = top + 17 + marker_index * 21
        elements.extend(
            [
                f'<line x1="{x:.1f}" y1="{top}" x2="{x:.1f}" y2="{top + plot_height}" stroke="{color}" stroke-width="2" stroke-dasharray="7 5"/>',
                f'<text x="{x + 7:.1f}" y="{label_y}" fill="{color}" font-size="12" font-weight="600">{label}: {value:,.0f} nt</text>',
            ]
        )

    elements.extend(
        [
            f'<text x="{left + plot_width / 2}" y="{height - 48}" text-anchor="middle" fill="{_INK}" font-size="13">CDS length (nucleotides)</text>',
            f'<text x="22" y="{top + plot_height / 2}" text-anchor="middle" fill="{_INK}" font-size="13" transform="rotate(-90 22 {top + plot_height / 2})">Number of CDS</text>',
        ]
    )
    _footer(elements, width, height)
    path.write_text("\n".join(elements) + "\n", encoding="utf-8")


def write_comparison_overview(path: Path, profiles: Sequence[Mapping[str, object]]) -> None:
    """Write small-multiple dot plots for comparable normalized metrics."""

    metrics = (
        ("GC content", "gc_percent", "%"),
        ("Coding density", "coding_density_percent", "%"),
        ("COG coverage", "cog_coverage_percent", "%"),
        ("Hypothetical CDS", "hypothetical_percent", "%"),
        ("Gene names", "gene_name_percent", "%"),
        ("CDS density", "cds_per_mb", " / Mb"),
    )
    width, panel_width = 1200, 520
    left, top = 160, 120
    row_height = max(72, 18 * len(profiles) + 34)
    height = top + len(metrics) * row_height + 80
    elements = _header(
        width, height, "Normalized annotation overview",
        "Comparable percentages and rates; each row uses its own labelled scale",
    )
    colors = (_BLUE, _TEAL, "#7c3aed", "#c2410c", "#be123c", "#0369a1")
    for metric_index, (label, key, suffix) in enumerate(metrics):
        available_profiles = [
            profile for profile in profiles
            if key != "cog_coverage_percent" or profile.get("cog_data_available", True)
        ]
        values = [float(profile[key]) for profile in available_profiles]
        maximum = max(values, default=1)
        scale_max = 100.0 if suffix == "%" else max(1.0, maximum * 1.08)
        y = top + metric_index * row_height
        elements.extend(
            [
                f'<text x="{left - 18}" y="{y + 6}" text-anchor="end" fill="{_INK}" font-size="14" font-weight="600">{escape(label)}</text>',
                f'<line x1="{left}" y1="{y}" x2="{left + panel_width}" y2="{y}" stroke="{_GRID}" stroke-width="2"/>',
                f'<text x="{left}" y="{y + 27}" text-anchor="middle" fill="{_MUTED}" font-size="11">0</text>',
                f'<text x="{left + panel_width}" y="{y + 27}" text-anchor="middle" fill="{_MUTED}" font-size="11">{scale_max:.0f}{escape(suffix)}</text>',
            ]
        )
        for profile_index, profile in enumerate(profiles):
            color = colors[profile_index % len(colors)]
            offset = (profile_index - (len(profiles) - 1) / 2) * 18
            full_label = str(profile["label"])
            visible_label = _short_label(full_label)
            if key == "cog_coverage_percent" and not profile.get("cog_data_available", True):
                elements.append(
                    f'<text x="{left + panel_width + 18}" y="{y + offset + 4:.1f}" fill="{_MUTED}" font-size="11"><title>{escape(full_label)}: not available</title>{escape(visible_label)}: not available</text>'
                )
                continue
            value = float(profile[key])
            x = left + panel_width * value / scale_max if scale_max else left
            elements.extend(
                [
                    f'<circle cx="{x:.1f}" cy="{y + offset:.1f}" r="6" fill="{color}"><title>{escape(str(profile["label"]))}: {value:.2f}{escape(suffix)}</title></circle>',
                    f'<text x="{left + panel_width + 18}" y="{y + offset + 4:.1f}" fill="{color}" font-size="11"><title>{escape(full_label)}: {value:.2f}{escape(suffix)}</title>{escape(visible_label)}: {value:.2f}{escape(suffix)}</text>',
                ]
            )
    _footer(elements, width, height)
    path.write_text("\n".join(elements) + "\n", encoding="utf-8")


def write_cog_comparison(
    path: Path,
    profiles: Sequence[Mapping[str, object]],
    category_names: Mapping[str, str],
) -> None:
    """Write a two-genome COG delta chart or a multi-genome heatmap."""

    categories = sorted(
        set().union(*(profile["cog_category_percentages"] for profile in profiles))
    )
    if len(profiles) == 2:
        _write_cog_delta(path, profiles, categories, category_names)
    else:
        _write_cog_heatmap(path, profiles, categories, category_names)


def _write_cog_delta(
    path: Path,
    profiles: Sequence[Mapping[str, object]],
    categories: Sequence[str],
    category_names: Mapping[str, str],
) -> None:
    """Write percentage-point COG differences for exactly two genomes."""

    width, left, right, top, row_height = 1200, 390, 110, 110, 31
    height = max(250, top + len(categories) * row_height + 75)
    deltas = [
        float(profiles[1]["cog_category_percentages"].get(category, 0))
        - float(profiles[0]["cog_category_percentages"].get(category, 0))
        for category in categories
    ]
    bound = max((abs(value) for value in deltas), default=1) or 1
    center = left + (width - left - right) / 2
    half_width = (width - left - right) / 2
    description = (
        f'Percentage-point change from {profiles[0]["label"]} to {profiles[1]["label"]}; '
        "multi-category proteins contribute to each category"
    )
    elements = _header(width, height, "COG functional-profile difference", description)
    elements.append(
        f'<line x1="{center}" y1="{top - 12}" x2="{center}" y2="{height - 62}" stroke="{_INK}"/>'
    )
    for index, (category, delta) in enumerate(zip(categories, deltas)):
        y = top + index * row_height
        bar_width = half_width * abs(delta) / bound
        x = center if delta >= 0 else center - bar_width
        color = _TEAL if delta >= 0 else _BLUE
        label = f"{category} - {category_names.get(category, 'Unclassified')}"
        elements.extend(
            [
                f'<text x="{left - 12}" y="{y + 17}" text-anchor="end" fill="{_INK}" font-size="12">{escape(label)}</text>',
                f'<rect x="{x:.1f}" y="{y}" width="{bar_width:.1f}" height="21" rx="4" fill="{color}"/>',
                f'<text x="{center + (bar_width + 7 if delta >= 0 else -bar_width - 7):.1f}" y="{y + 16}" text-anchor="{("start" if delta >= 0 else "end")}" fill="{_INK}" font-size="11">{delta:+.2f} pp</text>',
            ]
        )
    _footer(elements, width, height)
    path.write_text("\n".join(elements) + "\n", encoding="utf-8")


def _write_cog_heatmap(
    path: Path,
    profiles: Sequence[Mapping[str, object]],
    categories: Sequence[str],
    category_names: Mapping[str, str],
) -> None:
    """Write a dataset-by-category heatmap for three or more genomes."""

    width, left, top, cell_width, cell_height = 1200, 390, 130, 90, 31
    plot_width = max(1, len(profiles)) * cell_width
    width = max(width, left + plot_width + 60)
    height = max(270, top + len(categories) * cell_height + 75)
    maximum = max(
        (float(profile["cog_category_percentages"].get(category, 0)) for profile in profiles for category in categories),
        default=1,
    ) or 1
    elements = _header(
        width, height, "COG functional-profile heatmap",
        "Percentage of all observed COG category assignments in each dataset",
    )
    for profile_index, profile in enumerate(profiles):
        x = left + profile_index * cell_width + cell_width / 2
        full_label = str(profile["label"])
        elements.append(
            f'<text x="{x}" y="{top - 16}" text-anchor="middle" fill="{_INK}" font-size="12"><title>{escape(full_label)}</title>{escape(_short_label(full_label, 12))}</text>'
        )
    for category_index, category in enumerate(categories):
        y = top + category_index * cell_height
        label = f"{category} - {category_names.get(category, 'Unclassified')}"
        elements.append(
            f'<text x="{left - 12}" y="{y + 20}" text-anchor="end" fill="{_INK}" font-size="12">{escape(label)}</text>'
        )
        for profile_index, profile in enumerate(profiles):
            value = float(profile["cog_category_percentages"].get(category, 0))
            intensity = value / maximum
            red = round(239 - 183 * intensity)
            green = round(246 - 57 * intensity)
            blue = round(255 - 7 * intensity)
            x = left + profile_index * cell_width
            text_color = "#ffffff" if intensity > 0.55 else _INK
            elements.extend(
                [
                    f'<rect x="{x}" y="{y}" width="{cell_width - 3}" height="{cell_height - 3}" rx="4" fill="rgb({red},{green},{blue})"><title>{escape(str(profile["label"]))}: {value:.2f}%</title></rect>',
                    f'<text x="{x + (cell_width - 3) / 2:.1f}" y="{y + 20}" text-anchor="middle" fill="{text_color}" font-size="11">{value:.2f}%</text>',
                ]
            )
    _footer(elements, width, height)
    path.write_text("\n".join(elements) + "\n", encoding="utf-8")
